name: Update CVE KEV Feeds

on:
  schedule:
    - cron: '0 10,16 * * *'
  workflow_dispatch:

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install requests pytz

      - name: Fetch and Process Latest Vulnerabilities
        run: python kev.py

      - name: Debug File Generation
        run: |
          echo "Current Directory: $(pwd)"
          ls -lah  # Check if JSON is created/

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add known_exploited_vulnerabilities.json
          git status  # Show changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update CISA KEV JSON feeds" && git push)
