name: Download CISA KEV JSON Feed

on:
  schedule:
    # Runs the workflow every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  download-kev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download CISA KEV JSON Feed
        run: |
          python -c "
import requests

kev_url = 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json'
output_file = 'output/CISA-KEV.json'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
    'Accept': 'application/json',
    'Accept-Language': 'en-US,en;q=0.5',
    'Connection': 'keep-alive',
    'Referer': 'https://www.cisa.gov/',
}

response = requests.get(kev_url, headers=headers)

if response.status_code == 200:
    with open(output_file, 'wb') as f:
        f.write(response.content)
    print(f'File downloaded successfully and saved as {output_file}')
else:
    print(f'Failed to download file. Status code: {response.status_code}')
          "

      - name: Commit and push downloaded file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output/CISA-KEV.json
          git commit -m "Download updated CISA KEV JSON Feed"
          git push
